<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
		<link rel="stylesheet" type="text/css" href="/public/css/style.css">
		<title>Pendu</title>
	</head>
	<body>
		<div id="content">
			<div class="col-12 d-flex justify-content-center align-items-center">
				<div class="column">
					
					<div class="container mt-5">
						<div id="frame" class="d-flex justify-content-center">
							<img class="d-flex justify-content-center" src="/public/img/hangman-<?= $lifePoints ?>.jpg" alt="<?= 'lifePoints: ' . $lifePoints ?>" id="hangman">
						</div>
					</div>
					<p class="lifepoints my-5 d-flex justify-content-center">Life points: <span id="lifePoints"><?= '&nbsp;' .  $lifePoints ?></span></p>
					<div id="result"></div>
					<?php foreach($split as $key => $letter) : ?>
						<span class="btn" data-letter="<?= $letter ?>">_</span>
					<?php endforeach; ?>
					
				</div>
			</div>
		</div>
		
		<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
		<script>
			<?= require('public/js/pendu.js'); ?>
		</script>
	</body>
</html>